// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBShCrkNeOBjg7cYIRzXHr0AedWvj8gVd8',
    appId: '1:901837765803:web:8d7fccaf96ce844c994bee',
    messagingSenderId: '901837765803',
    projectId: 'chat-8b695',
    authDomain: 'chat-8b695.firebaseapp.com',
    storageBucket: 'chat-8b695.appspot.com',
    measurementId: 'G-HRMM0PXWM9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbUis08xnefqjSMw2nCgfwavejpGwQeWk',
    appId: '1:901837765803:android:fbc9c130325fee12994bee',
    messagingSenderId: '901837765803',
    projectId: 'chat-8b695',
    storageBucket: 'chat-8b695.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoeyfr_uX4GIYNmTvVhmdmm2gPZnAo-2Q',
    appId: '1:901837765803:ios:515cf6982d813b2b994bee',
    messagingSenderId: '901837765803',
    projectId: 'chat-8b695',
    storageBucket: 'chat-8b695.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoeyfr_uX4GIYNmTvVhmdmm2gPZnAo-2Q',
    appId: '1:901837765803:ios:636d3002aa34422f994bee',
    messagingSenderId: '901837765803',
    projectId: 'chat-8b695',
    storageBucket: 'chat-8b695.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
